server:
  port: 8081
  servlet:
    context-path: /
  address: 0.0.0.0

vendor:
  dfs:
    sftp:
      user: "vagrant"
      password: "vagrant"
      host: "192.168.0.16"
      base: "/home/vagrant"
