apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-hammer-app
  namespace: prod
  labels:
    k8s.kuboard.cn/layer: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-hammer-app
  template:
    metadata:
      labels:
        app: one-hammer-app
    spec:
      # nodeSelector:
      #   online: "true"
      containers:
        - name: one-hammer-app
          image: www.hongwangtech.com:8088/one-hammer-app:prod
          imagePullPolicy: Always
          command: [ "/bin/bash" ]
          args: [ "/opt/app/docker-entrypoint.sh", "show" ]
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1024m"
          ports:
            - containerPort: 8080


